In [67]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import re

In [68]:
df = pd.read_csv('./jobstreet_all_job_dataset.csv',encoding='ISO-8859-1')

In [69]:
# things to achieve
# 1. company - similarity (consistent letter case, only sdn bhd capital)
# 2. description can be important but we skip that for now
# 3. location - state become short form, make new column for district
# state - 0 - kl 1 - johor (exp) , district 11 - johor bahru 12 - kulai 01 - klcc
# 4. manufacture - change to number
# 5. subcategory - dump or important?
# 6. role - kiv, maybe - rank their role, executive, administrator, lead, assistant
# 7. salary - to common format
# 8. date - to common format

In [70]:
# 1. company - similarity (consistent letter case, only sdn bhd capital)
df['company'] = df['company'].str.title()

def format_sdn_bhd(company_name):
    if pd.isna(company_name) or re.search("Sdn..*Bhd.", company_name, flags=re.IGNORECASE):  
        return company_name
    company_name = re.sub(r'\b(Sdn)\b', r'\1.', company_name, flags=re.IGNORECASE)
    company_name = re.sub(r'\b(Bhd)\b', r'\1.', company_name, flags=re.IGNORECASE)
    
    return company_name 

df['company'] = df['company'].apply(format_sdn_bhd)

In [71]:
# 2. description can be important but we skip that for now
# 3. location - state become short form, make new column for district
# state - 0 - kl 1 - johor (exp) , district 11 - johor bahru 12 - kulai 01 - klcc
# Define the mapping of location names to codes
state_mapping = {
    "johor": "01",
    "kedah": "02",
    "kelantan": "03",
    "melaka": "04",
    "negeri sembilan": "05",
    "pahang": "06",
    "perak": "08",
    "perlis": "09",
    "pulau pinang": "07",
    "penang": "07",
    "sabah": "12",
    "sarawak": "13",
    "selangor": "10",
    "terengganu": "11",
    "kuala lumpur": "14",
    "labuan": "15",
    "putrajaya": "16"

}

dicstrict_mapping = {
    "johor": {
        "batu pahat": "0101",
        "johor bahru": "0102",
        "kluang": "0103",
        "kota tinggi": "0104",
        "kulai": "0105",
        "mersing": "0106",
        "muar": "0107",
        "pontian": "0108",
        "segamat": "0109",
        "tangkak": "0110",
    },
    "kedah": {
        "baling": "0201",
        "bandar baharu": "0202",
        "kota setar": "0203",
        "kuala muda": "0204",
        "kubang pasu": "0205",
        "kulim": "0206",
        "langkawi": "0207",
        "padang terap": "0208",
        "pendang": "0209",
        "pokok sena": "0210",
        "sik": "0211",
        "yan": "0212",
    },
    "kelantan": {
        "bachok": "0301",
        "gua musang": "0302",
        "jeli": "0303",
        "kota bharu": "0304",
        "kuala krai": "0305",
        "machang": "0306",
        "pasir mas": "0307",
        "pasir puteh": "0308",
        "tanah merah": "0309",
        "tumpat": "0310",
    },
    "melaka": {
        "alor gajah": "0401",
        "jasin": "0402",
        "melaka tengah": "0403",
    },
    "negeri sembilan": {
        "jelebu": "0501",
        "jempol": "0502",
        "kuala pilah": "0503",
        "port dickson": "0504",
        "rembau": "0505",
        "seremban": "0506",
        "tampin": "0507",
    },
    "pahang": {
        "bentong": "0601",
        "bera": "0602",
        "cameron highlands": "0603",
        "jerantut": "0604",
        "kuantan": "0605",
        "lipis": "0606",
        "maran": "0607",
        "pekan": "0608",
        "raub": "0609",
        "rompin": "0610",
        "temerloh": "0611",
    },
    "perak": {
        "bagan datuk": "0801",
        "batang padang": "0802",
        "hilir perak": "0803",
        "hulu perak": "0804",
        "kampar": "0805",
        "kerian": "0806",
        "kinta": "0807",
        "kuala kangsar": "0808",
        "larut, matang and selama": "0809",
        "manjung": "0810",
        "muallim": "0811",
        "perak tengah": "0812",
    },
    "perlis": {
        "kangar": "0901",
    },
    "pulau pinang": {
        "penang island": "0701",
        "seberang perai": "0702",
    },
    "sabah": {
        "beaufort": "1201",
        "beluran": "1202",
        "kalabakan": "1203",
        "keningau": "1204",
        "kinabatangan": "1205",
        "kota belud": "1206",
        "kota kinabalu": "1207",
        "kota marudu": "1208",
        "kuala penyu": "1209",
        "kudat": "1210",
        "kunak": "1211",
        "lahad datu": "1212",
        "nabawan": "1213",
        "papar": "1214",
        "penampang": "1215",
        "pitas": "1216",
        "putatan": "1217",
        "ranau": "1218",
        "sandakan": "1219",
        "semporna": "1220",
        "sipitang": "1221",
        "tambunan": "1222",
        "tamparuli": "1223",
        "tenom": "1224",
        "tongod": "1225",
        "tuaran": "1226",
        "telupid": "1227",
        "paitan": "1228",
    },
    "sarawak": {
        "betong": "1301",
        "bintulu": "1302",
        "kapit": "1303",
        "kuching": "1304",
        "limbang": "1305",
        "miri": "1306",
        "mukah": "1307",
        "samarahan": "1308",
        "sarikei": "1309",
        "serian": "1310",
        "sibu": "1311",
        "sri aman": "1312",
        "bario": "1313",
        "lawas": "1314",
        "marudi": "1315",
    },
    "selangor": {
        "gombak": "1001",
        "hulu langat": "1002",
        "hulu selangor": "1003",
        "klang": "1004",
        "kuala langat": "1005",
        "kuala selangor": "1006",
        "petaling": "1007",
        "sabak bernam": "1008",
        "sepang": "1009",
    },
    "terengganu": {
        "besut": "1101",
        "dungun": "1102",
        "hulu terengganu": "1103",
        "kemaman": "1104",
        "kuala nerus": "1105",
        "kuala terengganu": "1106",
        "marang": "1107",
        "setiu": "1108",
    },
    "kuala lumpur": {
        "bukit bintang": "1401",
        "cheras": "1402",
        "setiawangsa": "1403",
        "kepong": "1404",
    },
    "labuan": {
        "labuan": "1501",
    },
    "putrajaya": {
        "putrajaya": "1601",
    },
}

kuala_lumpur_areas = [
    "bukit kiara",
    "bukit jalil",
    "bandar malaysia",
    "maluri",
    "kl eco city",
    "kucai lama",
    "shamelin perkasa",
    "sungai besi",
    "ampang",
    "mid valley city",
    "bangsar",
    "mont kiara",
    "taman oug",
    "bandar menjalara",
    "bandar baru sentul",
    "sri hartamas",
    "damansara heights",
    "taman tun dr ismail",
    "setapak",
    "kepong",
    "wangsa maju",
    "segambut",
    "taman desa",
    "taman connaught",
    "kuchai lama",
    "alam damai",
    "desa parkcity",
    "kampung malaysia raya",
    "seputeh",
    "bandar tun razak",
    "tun razak exchange",
    "titiwangsa",
    "setiawangsa",
    "kuala lumpur city centre",
    "bukit bintang",
    "chinatown",
    "little india",
    "brickfields"
]

selangor_areas = [
    "shah alam",
    "petaling jaya",
    "subang jaya",
    "klang",
    "kajang",
    "rawang",
    "puchong",
    "seri kembangan",
    "cyberjaya",
    "putrajaya",
    "selayang",
    "gombak",
    "damansara",
    "ampang jaya",
    "semenyih",
    "sungai buloh",
    "balakong",
    "banting",
    "sepang",
    "bukit jelutong",
    "bandar sunway",
    "bandar utama",
    "taman melawati",
    "tropicana",
    "port klang"
]

def get_location_info(location):
    if pd.isna(location):
        return pd.Series([None, None, None])
    
    location = location.lower()
    
    for keyword in selangor_areas:
        if re.search(keyword, location, flags=re.IGNORECASE):
            return pd.Series(["10", "10", location])
    
    for keyword in kuala_lumpur_areas:
        if re.search(keyword, location, flags=re.IGNORECASE):
            return pd.Series(["14", "14", location])
    
    for state, code in state_mapping.items():
        if state in location:
            return pd.Series([code, None, location])
        
    for state, districts in dicstrict_mapping.items():
        for district, district_code in districts.items():
            if district in location:
                return pd.Series([state_mapping[state], district_code, location])
    
    return pd.Series([None, None, location])

df[['state', 'district', 'location_desc']] = df['location'].apply(get_location_info)

In [72]:
# 4. manufacture - change to number
def get_numbers(category_list):
    category_mapping = {}
    for index, category in enumerate(category_list):
        category_mapping[category] = f"{index:02d}"
    return category_mapping

category_list = df["category"].unique()
category_list = sorted(category_list)
category_mapping = get_numbers(category_list)

df['category'] = df['category'].map(category_mapping)

In [73]:
# 5. subcategory - dump or important?
# 6. role - kiv, maybe - rank their role, executive, administrator, lead, assistant

In [74]:
# 7. salary - to common format
# create 3 column - minimum, maximum, type_salary, benefit
# common usage word been map
type_month_list= ["per month"," p.m.","monthly","month"]
type_year_list= ["per year","per annum"," p.a."]
type_hour_list= ["per hour"," p.h."]

conversion_rates = {
    "sgd": 3.3162,  
    "$": 4.506,    
    "euro": 4.6822,
    "myr": 1.0
}

def get_type_salary(salary):
    if isinstance(salary, str):

        for keyword in type_month_list:
            if re.search(keyword, salary, flags=re.IGNORECASE):
                return "monthly"
        
        for keyword in type_year_list:
            if re.search(keyword, salary, flags=re.IGNORECASE):
                return "yearly"
        
        for keyword in type_hour_list:
            if re.search(keyword, salary, flags=re.IGNORECASE):
                return "hourly"
    
    return "monthly"

def change_currency(salary, numbers):
    if isinstance(salary, str):
        converted_numbers = []
        currency = "myr"
        
        if re.search(r'\$', salary):
            currency = "$"
        elif re.search(r'euro', salary, flags=re.IGNORECASE):
            currency = "euro"
        elif re.search(r'sgd', salary, flags=re.IGNORECASE):
            currency = "sgd"
        elif re.search(r'myr', salary, flags=re.IGNORECASE):
            currency = "myr"
        
        for num in numbers:
            if 'k' in num.lower():
                num = float(num.lower().replace('k', '')) * 1000
            elif ',' in num:
                num = num.replace(',', '')
            elif '.' in num:
                num = float(num.replace('.', '')) * 1000
            converted_numbers.append(float(num) * conversion_rates.get(currency, 1.0))
        
        return converted_numbers
    
    return []

def extract_salaries(salary):
    if isinstance(salary, str):

        salary = re.sub(r'[^\x00-\x7F]+', ' ', salary)       

        numbers = re.findall(r'\d+(?:,\d+)*(?:\.\d+)?[kK]?', salary)
        
        if not numbers:
            return pd.Series([None, None, None, salary])
        
        extracted_nums = change_currency(salary, numbers)

        min_salary = extracted_nums[0] if len(extracted_nums) > 1 else None
        max_salary = extracted_nums[1] if len(extracted_nums) > 1 else extracted_nums[0]

        return pd.Series([min_salary, max_salary, get_type_salary(salary), None])
    
    return pd.Series([None, None, None, None])


df[['min_salary', 'max_salary', 'type_salary', 'benefit']] = df['salary'].apply(extract_salaries)

In [75]:
# 8. date - to common format
df['date'] = pd.to_datetime(df['listingDate']).dt.date

In [76]:
# # drop for missing values
df = df.dropna(subset=['min_salary', 'max_salary'], how='all')

In [77]:
df = df[['job_id','job_title','company','state','district','location_desc','category','role', 'min_salary', 'max_salary','type_salary', 'date']]
df.to_csv('clean_dataset1.csv')